name: workflow-2
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  Job2:
    name: Reading output from workflow 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get output from workflow 1 using gihub cli
        run: |
          echo "${secrets.GITHUB_TOKEN}" > mytoken.txt
          gh auth login --with-token < mytoken.txt
          RUN_ID=$(gh workflow view workflow-1.yml | grep -m1 "completed" | awk '{print $8}')
          gh run view ${RUN_ID} --log > output.txt
          sed 's/^.*Z //g' output.txt > sanitized_log.txt

      - name: Read output from workflow 1
        run: |
          COMMIT_HASH=$(grep '^commithash id is ' sanitized_log.txt | sed 's/commithash id is //g')
          echo "Commit hash from workflow-1 is ${COMMIT_HASH}"

          DEPLOY_ID=$(grep -E '^[[:digit:]]{9}' sanitized_log.txt )  
          echo "Deployment id from workflow-1 is ${DEPLOY_ID}"

          STATUS=$(grep -E '^(pending|queued)' sanitized_log.txt)
          echo "Status from workflow-1 is ${STATUS}"
